hash-format = "sha256"

[[files]]
file = "credits.txt"
hash = "d627e1b20336f5b262b794208b578b23f43f1f9d6fdf278bd07f48131aa38324"

[[files]]
file = "datapacks/armor-statues.pw.toml"
hash = "c807c45c9addc1a0765058abcadacb25a1a17deb0623a1985c4bf1a22d22a90a"
metafile = true

[[files]]
file = "datapacks/custom-nether-portals.pw.toml"
hash = "976b5f063cf299cefecf26b5a0cdb6243eca4fc15f4d62f84832f5cd4a3c1b70"
metafile = true

[[files]]
file = "datapacks/dynamic-lights.pw.toml"
hash = "977aac6c822343e328df984b939eaba3b8f58d5a3181b7cd6fd6032fc8913034"
metafile = true

[[files]]
file = "datapacks/veinminer-enchantment.pw.toml"
hash = "7a655fa15fb441d331044cfe933f4b140abdcf095c0d69f70cc80d704fb7d1ef"
metafile = true

[[files]]
file = "datapacks/veinminer.pw.toml"
hash = "042d273e0873bc9c33fffebef698464246824858a31f1a4ed6e6785b704491eb"
metafile = true

[[files]]
file = "mods/alternate-current.pw.toml"
hash = "221c3fe02674f1208273f0a1a376ae3a0090dacd9093a95e79988e5a4a495d2d"
metafile = true

[[files]]
file = "mods/ambient-environment.pw.toml"
hash = "c2da1008c8108a56f1a12d50a23559841f4be5867fb8eb2d6098807daf3f2468"
metafile = true

[[files]]
file = "mods/appleskin.pw.toml"
hash = "417e4f42790407e6fb4dfcb03cd4abcdf3aa00f4dcef3f3a2edec1a3e1a9a3ef"
metafile = true

[[files]]
file = "mods/architectury-api.pw.toml"
hash = "848c49f2ead5e1e71d7be95d2d9e1cb992631faf91500b9c59e72d61afca33fd"
metafile = true

[[files]]
file = "mods/balm.pw.toml"
hash = "08a4039bac6efd14b5257ac3df87680568d1372d4ab693e03a8aab88361580b9"
metafile = true

[[files]]
file = "mods/betterf3.pw.toml"
hash = "cbc0973dadd8e4a191ce8e819f212bcfb58708885b4a46a9de7afa29e71aadad"
metafile = true

[[files]]
file = "mods/bluemap-sign-markers.pw.toml"
hash = "914bfebc448db591ceb502df3ed83fed8639e34b20e6e16e638f5207abc8886e"
metafile = true

[[files]]
file = "mods/bluemap.pw.toml"
hash = "0fab2a26e6692d71537da9565dd87137504ddb34653136fd9f7a7df084d47575"
metafile = true

[[files]]
file = "mods/c2me-fabric.pw.toml"
hash = "62e99d55c3f95e732fbbb23572c70bd030a6c89f90844b8a74d1e527c0183696"
metafile = true

[[files]]
file = "mods/carpet.pw.toml"
hash = "13cd4e9e1d7a596072ce69a9bafd97e3f04bebc137d220ac062fe90968286453"
metafile = true

[[files]]
file = "mods/chunky.pw.toml"
hash = "64c483fe6597534270aac57d7cd3f59928641b97de649312a14d392b5343e483"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "df15648dd4d4e27dd0c45ab4e78277c45886b77a698b129f4ce2d2bc337f7044"
metafile = true

[[files]]
file = "mods/clumps.pw.toml"
hash = "84010019ebe7f20274f0c6c55aa3dd254e335098f006bed0d4f0a189ac12fa64"
metafile = true

[[files]]
file = "mods/collective.pw.toml"
hash = "a598c30d51764141713c3871c44497bc420d602f9a378c28fc8f49c269fac386"
metafile = true

[[files]]
file = "mods/controlify.pw.toml"
hash = "853087309c5b08115038d1f349928cd95370926956ae7a293b810f2b2711e7f3"
metafile = true

[[files]]
file = "mods/craftpresence.pw.toml"
hash = "f5d0d082d4d3064da7dee4ad1881788f4782a804a2e1b034c2a903e2b68b97eb"
metafile = true

[[files]]
file = "mods/crops-love-rain.pw.toml"
hash = "446a273b3868578eb7f511b585a2648519a3487de209557b222910e53872b72c"
metafile = true

[[files]]
file = "mods/dataloader.pw.toml"
hash = "7c6243cb0903bb8f900eaa0d64b2cd34d98630780065bc2d2b05e4d19fc2ce32"
metafile = true

[[files]]
file = "mods/debugify.pw.toml"
hash = "f605331d864b266407b9d4486a4355febbc80b5e2e6ef75e4d92d45d2b29bc8f"
metafile = true

[[files]]
file = "mods/distanthorizons.pw.toml"
hash = "2ad8cd5745efd0bd0f7f32f060bec092a7b2ef8ac3c6163033193a8277012e43"
metafile = true

[[files]]
file = "mods/dynamic-fps.pw.toml"
hash = "d1a2a4ef509bb718243d16e2950b1289f286428c3067685f4ef40f4ec4f8a0a6"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "a63069aac3fc618562c8f4fa4f76e0bd3625a90f53d1dc3ff4974862d54dde20"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "687d9f69912b725a879bf3b4da8fb3f63eead93e4ce3e719c2be67d56b70c0b5"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "97e7fb0bf5c563366b7c6121fa2decb67597107e5594932c6a098cccc980629e"
metafile = true

[[files]]
file = "mods/fallingleaves.pw.toml"
hash = "937e9c66908ede3a91ffce2196385789575527324973b75ab10a35f4e4524651"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "1ef554f7a8d5f7ed4bc21316e034eeef3430dc306012c0a706bd4c3e4ac253aa"
metafile = true

[[files]]
file = "mods/floodgate.pw.toml"
hash = "b9ccdada3af888348b8c8eb757ea3c528bd20db5f0beef533fd6c5eee651faa6"
metafile = true

[[files]]
file = "mods/fsit.pw.toml"
hash = "dbb0827e023f34d8221c4b25c05b3dedea956193c63ede1a56f53ccdc6bef800"
metafile = true

[[files]]
file = "mods/geophilic.pw.toml"
hash = "c73fc3680d04bd42fafb0ac3e5e2dfc9e50cff44453ecf91b1bebca6da5107eb"
metafile = true

[[files]]
file = "mods/geyser.pw.toml"
hash = "039a49f9812f49e8b15e13cb8901120701f4e65ad64ed266130eec1ec357f410"
metafile = true

[[files]]
file = "mods/image2map.pw.toml"
hash = "bb831e6e9b6a572a7ebccaefff6358cdba9053fc5a647974e4d5df85be0f10c4"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
hash = "e03fc0b0c151c5c072ac399d27b5c4268a093c41be73f3b1578d050bb49211f3"
metafile = true

[[files]]
file = "mods/jade.pw.toml"
hash = "114968e70a3e2c2f7a33db6ed305256585353361a28210a0b872df52fc5542aa"
metafile = true

[[files]]
file = "mods/jamlib.pw.toml"
hash = "3bf0bdb21b300641c64e8d9a86a6af94105659432d9a8c14584668845db28c07"
metafile = true

[[files]]
file = "mods/kleeslabs.pw.toml"
hash = "f6e1752471b0eb6445ded46d748b876db3b3cda2e3c5f2195a256d612d2fd55a"
metafile = true

[[files]]
file = "mods/lambdynamiclights.pw.toml"
hash = "c716469739cf0e6c33cd1c71ce67cd942a23395b5ecb3f04b59ddba87e0347f6"
metafile = true

[[files]]
file = "mods/ledger.pw.toml"
hash = "252b12d6a5548adcf3a18607a014f76e7906d76db09e7235652c39d2eccd5b2e"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "df9d69dc784ef61e99064407952d34c294f62fe1155b5260f825bd9a82e2f3a2"
metafile = true

[[files]]
file = "mods/modernfix.pw.toml"
hash = "a874985359eaa4317b3242136fe65b86207a6d5ab55e0b4aa8f37b90727f0487"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "88c6edc1712f4f0cd915cd723b9e0296924d454b3855a719d2962103b2b92bea"
metafile = true

[[files]]
file = "mods/monsters-in-the-closet.pw.toml"
hash = "febe90046102708c065c23a8577039c1dc6786de1ed0f0378e4647b22669659e"
metafile = true

[[files]]
file = "mods/mouse-tweaks.pw.toml"
hash = "4aef3c4dbc01c945f4a30f63c03607aad77d16ab194983510c10ce516312e258"
metafile = true

[[files]]
file = "mods/mru.pw.toml"
hash = "eaa0d06f31b5cd5bcac139b8b41ddd985831f35f7d633d12355d1d15735c3a84"
metafile = true

[[files]]
file = "mods/netherportalfix.pw.toml"
hash = "ace9ce441fc72217675c9192315d9126e200341491f65058cf461f7e5a49a3e6"
metafile = true

[[files]]
file = "mods/noisium.pw.toml"
hash = "85ae542e2ccfb61bcdd3aa55b1a56436782687ba63388e249cb98376737045d4"
metafile = true

[[files]]
file = "mods/placeholder-api.pw.toml"
hash = "6b2abdc14fca0b9b42b5678e7c65af8b93d5032f0e4b0d2fbd93295903489d50"
metafile = true

[[files]]
file = "mods/rightclickharvest.pw.toml"
hash = "645622d16ed124e89e859ff3bf3df11503375d09d0970c3aa38d03bf2bdb3fdd"
metafile = true

[[files]]
file = "mods/scaffolding-drops-nearby.pw.toml"
hash = "ff26c7c9007bb25a092b1b7ed93c66973610fe0eeebee1f8f956dbdad5d5fe85"
metafile = true

[[files]]
file = "mods/screenshot-to-clipboard.pw.toml"
hash = "86ff9b67d90f046045619aa571df7bad909e480711c5d8b8967e3efca84ad16a"
metafile = true

[[files]]
file = "mods/snow-under-trees-remastered.pw.toml"
hash = "82bfd89ec4a0468023b4fcadbdb407fb9f991f80d9776e89d25a60e44fae2e7d"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "09d2dbee70e91e8859e6f62e4181a80264d6dd24cc686fbedb93dda9f69fdfe6"
metafile = true

[[files]]
file = "mods/spark.pw.toml"
hash = "16e02f523c718baefd9dd42b24bd1aeb7c1142ff0e46a512e958284158bd8461"
metafile = true

[[files]]
file = "mods/toggle-item-frames.pw.toml"
hash = "2568a0352dad7a43e4f855e5f0e58a9788ed7806e1a0f3e8f7526fc648e7fa25"
metafile = true

[[files]]
file = "mods/unilib.pw.toml"
hash = "a5f9299d97fa94f981726417671569eea366d283720cd08e7e4e20c07de0bb60"
metafile = true

[[files]]
file = "mods/unloaded-activity.pw.toml"
hash = "17f54e17c7274aa20b5392825a2b1c756b3bb4e3c655954bee501eda2cd3e91b"
metafile = true

[[files]]
file = "mods/viabackwards.pw.toml"
hash = "adbb5b3daf8415c61cdf4f2be0c34c92c38a003b3fe6e79403f88322dad996d9"
metafile = true

[[files]]
file = "mods/viafabric.pw.toml"
hash = "d6b857d2c020eea18f40aa4406c6a35432ef7f6ff97a3033232c7dfc559fa4ac"
metafile = true

[[files]]
file = "mods/viaversion.pw.toml"
hash = "210b7498c0d4011ff970c72ccb17d0d0002d3ac5c8295f424e24bf192890e09b"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
hash = "75b191c621b271734901f012011f22e0c8f5c21ee5de1bfa369ace9540fd1e76"
metafile = true

[[files]]
file = "mods/zoomify.pw.toml"
hash = "c9a5dca078d983e94d629ca4bf402fff78e364e5b5365ff43373d77eec268432"
metafile = true

[[files]]
file = "options.txt.pw.toml"
hash = "93228cfe61f6ece6d35e1e1dbb770cd99d6fd6c3712c691ca472c76ea7306e52"
metafile = true
preserve = true

[[files]]
file = "server.properties.pw.toml"
hash = "beb09539f76f513d082af7c345f3fd15bd15bcb81dd6f9c96fe86488f8127994"
metafile = true

[[files]]
file = "shaderpacks/bsl-shaders.pw.toml"
hash = "cfb57ffe639b04b5aee53ca280aad97e5c94395059a049a47b24af0660776904"
metafile = true

[[files]]
file = "shaderpacks/complementary-reimagined.pw.toml"
hash = "b90b25b61edd0dfe3bb3074e2343351c7a427d24bb1fa42c642a157b0fd887e4"
metafile = true
